## FILE: /home/syrinx/.zshrc
## AUTHOR: syrinx (copyleft 2012)

## COMMENT: set the default editor
export EDITOR='emacsclient -c -n'

## COMMENT: autocompletion ## FIX: customise this a bit more
autoload -Uz compinit
compinit

## COMMENT: keybinding style 
bindkey -e

## COMMENT: keybindings
bindkey "\e[3~" delete-char # NOTE: enables Del key.
## COMMENT: this stuff probably only works for urxvt
bindkey "\e[7~" beginning-of-line # NOTE: Home key to beginning of line.
bindkey "\e[8~" end-of-line # NOTE: End key to end of line.

## COMMENT: this allows to search only past commands beginning with the current input.
bindkey "^[[A" history-beginning-search-backward
bindkey "^[[B" history-beginning-search-forward

## COMMENT: prompt settings
autoload -U colors && colors
PROMPT="%{$fg[blue]%}%n@%m%{$reset_color%} [%{%B$fg[yellow]%}%1~%{%b%}%{$reset_color%}] %# "
RPROMPT="[%{$fg[yellow]%}%T%{$reset_color%}]"

## COMMENT: aliases
alias ls="ls -a --color=auto"
alias pacman="sudo pacman-color"

zstyle :compinstall filename '/home/syrinx/.zshrc'
